# Default values for vsl-chain-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

updateStrategy:
  type: RollingUpdate

networkId: 12553

jwt:
  path: "/config/jwt-secret.txt"

geth:
  genesis:
    path: /config/genesis.json
    url: ""
  # Additional volumeMounts on the output Deployment definition.
  dataDir: /data

  volumeMounts: [ ]
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true
  env:
    GETH_VERBOSITY: "3"
    GETH_NODISCOVER: "true"
    GETH_MAXPEERS: "0"
    GETH_ROLLUP_DISABLETXPOOLGOSSIP: "true"
    # Allow for unprotected (non EIP155 signed) transactions to be submitted via RPC
    GETH_RPC_ALLOW_UNPROTECTED_TXS: "true"
    GETH_SYNCMODE: "full"
    # Blockchain garbage collection mode, only relevant in state.scheme: hash ("full","archive")
    GETH_GCMODE: "archive"
  envFrom: {}
  image:
    repository: rss3/op-geth
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "rss3-main-1ecad30"
  ports:
    auth:
      addr: "0.0.0.0"
      port: 8551
      vhosts: "*"
    http:
      enable: true
      addr: "0.0.0.0"
      port: 8545
      api: "web3,debug,eth,txpool,net,engine"
      vhosts: "*"
      cors: "*"
    websocket:
      enable: false
      addr: "0.0.0.0"
      port: 8546
      origins: "*"
      api: "web3,debug,eth,txpool,net,engine"
    metric:
      enable: true
      addr: "0.0.0.0"
      port: 7300
  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
  #   cpu: 100m
  #   memory: 128Mi

node:
  rollup:
    path: /config/rollup.json
    url: ""
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: [ ]
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true
  image:
    repository: rss3/op-node
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: a77d1f52fc3492bf21915bdff8ee8e0b5bd2cb8a
  ports:
    rpc:
      addr: "0.0.0.0"
      port: 9545
    p2p:
      addr: "0.0.0.0"
      port: 9003
    metric:
      enable: true
      addr: "0.0.0.0"
      port: 7301
  env:
    OP_NODE_SNAPSHOT_LOG: "/op_log/snapshot.log"
    OP_NODE_P2P_PRIV_PATH: "/config/opnode_p2p_priv.txt"
    OP_NODE_P2P_PEERSTORE_PATH: "/op_log/opnode_peerstore_db"
    OP_NODE_P2P_DISCOVERY_PATH: "/op_log/opnode_discovery_db"
    OP_NODE_P2P_AGENT: "rss3-vsl"
    OP_NODE_P2P_PEER_BANNING: "true"
    OP_NODE_LOG_LEVEL: "debug"
  envFrom: {}
  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
  #   cpu: 100m
  #   memory: 128Mi
## proxyd
proxyd:
  name: proxyd
  enabled: false
  image:
    repository: rss3/proxyd
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: a77d1f52fc3492bf21915bdff8ee8e0b5bd2cb8a

  ports:
    rpc:
      addr: "0.0.0.0"
      port: 9045

storage:
  hostPath: ""
  recovery:
    enabled: false
    snapshotName:
  persistentVolume:
    size: 500Gi
    storageClass: ""

    # Additional labels to apply to the created PersistentVolumeClaims.
    labels: {}
    # Additional annotations to apply to the created PersistentVolumeClaims.
    annotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  labels: {}
  annotations: {}

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false



nodeSelector: {}

tolerations: []

affinity: {}
