apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.hub.fullname" . }}
  labels:
    {{- include "node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.hub.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
      {{- if (and (eq .Values.hub.service.type "NodePort") (not (empty .Values.hub.service.nodePort))) }}
      nodePort: {{ .Values.hub.service.nodePort }}
      {{- end }}
  selector:
    {{- include "node.selectorLabels" (dict "context" . "name" .Values.hub.name) | nindent 4 }}
