{{- if .Values.broadcaster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "node.broadcaster.fullname" .}}
  labels:
    {{- include "node.labels" (dict "context" . "component" .Values.broadcaster.name "name" .Values.broadcaster.name) | nindent 4 }}
spec:
  type: {{ .Values.broadcaster.service.type }}
  ports:
    - port: {{ .Values.broadcaster.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.broadcaster.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
      {{- if (and (eq .Values.broadcaster.service.type "NodePort") (not (empty .Values.broadcaster.service.nodePort))) }}
      nodePort: {{ .Values.broadcaster.service.nodePort }}
      {{- end }}
  selector:
    {{- include "node.selectorLabels" (dict "context" . "name" .Values.broadcaster.name) | nindent 4 }}
{{- end }}