{{- if .Values.geth.recovery.enabled }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .Values.geth.recovery.snapshotName }}
spec:
  volumeSnapshotClassName: csi-gce-pd-snapshot-class
  source:
    volumeSnapshotContentName: {{ .Values.geth.recovery.snapshotName }}
{{- end }}
