apiVersion: v1
kind: Service
metadata:
  name: {{ template "vsl-chain-node.fullname" . }}
  labels:
    {{- include "vsl-chain-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      {{- if .Values.proxyd.enabled }}
      targetPort: {{ .Values.proxyd.ports.rpc.port }}
      {{- else }}
      targetPort: {{ .Values.geth.ports.http.port }}
      {{- end}}
      name: rpc
  selector:
    {{- include "vsl-chain-node.selectorLabels" . | nindent 4 }}