apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxyd.fullname" . }}
  labels:
    {{- include "proxyd.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.config | toToml | nindent 4 }}

