apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsl-chain.node.fullname" .}}
  annotations:
    avp.kubernetes.io/path: "kv/data/network/chain"
stringData:
  OP_NODE_L1_ETH_RPC: "<L1_ETH_RPC>"
  OP_NODE_L2_ENGINE_RPC: "http://localhost:8551"
  OP_NODE_L2_ENGINE_AUTH: "/config/jwt-secret.txt"
  OP_NODE_SEQUENCER_L1_CONFS: "10"
  OP_NODE_ROLLUP_CONFIG: "/config/rollup.json"
  OP_NODE_RPC_ADDR: "0.0.0.0"
  OP_NODE_RPC_PORT: "9545"
  OP_NODE_P2P_LISTEN_IP: "0.0.0.0"
  OP_NODE_P2P_LISTEN_TCP_PORT: "9003"
  OP_NODE_P2P_LISTEN_UDP_PORT: "9003"
  OP_NODE_SNAPSHOT_LOG: "/op_log/snapshot.log"
  OP_NODE_P2P_PRIV_PATH: "/config/opnode_p2p_priv.txt"
  OP_NODE_P2P_PEERSTORE_PATH: "/op_log/opnode_peerstore_db"
  OP_NODE_P2P_DISCOVERY_PATH: "/op_log/opnode_discovery_db"
  OP_NODE_P2P_AGENT: "rss3-vsl"
  OP_NODE_P2P_PEER_BANNING: "true"
  OP_NODE_METRICS_ENABLED: "true"
  OP_NODE_METRICS_PORT: "7301"
  OP_NODE_LOG_LEVEL: "debug"
  
  ## for sequencer node
  _OP_NODE_P2P_SEQUENCER_KEY: "<OP_NODE_P2P_SEQUENCER_KEY>"
  # OP_NODE_SEQUENCER_ENABLED: "true"
  # OP_NODE_SEQUENCER_STOPPED: "false"

  ## for rpc node
  OP_NODE_P2P_STATIC: "/ip4/10.0.0.20/tcp/9003/p2p/16Uiu2HAm3SZm4jiSNEgfeC4EHewVNBEVHvVyVeLuF3fuqRbiuJ8x"
