apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsl-chain.proposer.fullname" .}}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.global.vault.path }}"
    avp.kubernetes.io/secret-version: "{{ .Values.global.vault.version }}"
stringData:
  OP_PROPOSER_L1_ETH_RPC: "<L1_ETH_RPC>"
  OP_PROPOSER_ROLLUP_RPC: {{ (include "vsl-chain.geth.fullname" .) | printf "\"http://%s-write:9545\"" }}
  OP_PROPOSER_POLL_INTERVAL: "12s"
  OP_PROPOSER_PPROF_ENABLED: "true"
  OP_PROPOSER_PPROF_PORT: "6063"
  OP_PROPOSER_METRICS_ENABLED: "true"
  OP_PROPOSER_METRICS_PORT: "7303"
  OP_PROPOSER_ALLOW_NON_FINALIZED: "true"
  OP_PROPOSER_RPC_ENABLE_ADMIN: "true"
  OP_PROPOSER_LOG_LEVEL: "debug"
  
  # Address of the L2OutputOracle contract
  OP_PROPOSER_L2OO_ADDRESS: "<OP_PROPOSER_L2OO_ADDRESS>"
  OP_PROPOSER_SIGNER_ENDPOINT: "<OP_PROPOSER_SIGNER_ENDPOINT>"
  OP_PROPOSER_SIGNER_ADDRESS: "<OP_PROPOSER_SIGNER_ADDRESS>"
  OP_PROPOSER_SIGNER_TLS_CA: ""
  OP_PROPOSER_SIGNER_TLS_CERT: ""
  OP_PROPOSER_SIGNER_TLS_KEY: ""