{{- $processedDict := dict -}}
{{- range $path, $bytes := .Files.Glob "scripts/**" }}
{{- $name := base (dir $path) }}
{{- if not (hasKey $processedDict $name) -}}
{{ $_ := set $processedDict $name "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ $name }}
data:
{{ ($.Files.Glob (printf "scripts/%s/*" $name)).AsConfig | indent 2 }}
---
{{- end }}
{{- end }}