{{- if .Values.batcher.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.batcher.serviceAccount.name }}
  labels:
    {{- include "vsl-chain.labels" (dict "context" . "component" .Values.batcher.name "name" .Values.batcher.name) | nindent 4 }}
  {{- with .Values.batcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.batcher.serviceAccount.automountServiceAccountToken }}
{{- end }}
