{{- if (and .Values.core.enabled .Values.core.autoscaling.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "node.core.fullname" .}}
  labels:
    {{- include "node.labels" (dict "context" . "component" .Values.core.name "name" .Values.core.name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "node.fullname" . }}
  minReplicas: {{ .Values.core.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.core.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
