apiVersion: v1
kind: Service
metadata:
  name: {{ template "vsl-rpc.fullname" . }}-geth
  labels:
    {{- include "vsl-rpc.labels" . | nindent 4 }}
    app.kubernetes.io/component: geth
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.geth.ports }}
  ports:
    - protocol: TCP
      port: {{ .auth.port }}
      targetPort: {{ .auth.port }}
      name: auth
    {{- if .http.enable }}
    - protocol: TCP
      port: {{ .http.port }}
      targetPort: {{ .http.port }}
      name: http
    {{- end }}
    {{- if .websocket.enable }}
    - protocol: TCP
      port: {{ .websocket.port }}
      targetPort: {{ .websocket.port }}
      name: websocket
    {{- end }}
    {{- if .metric.enable }}
    - protocol: TCP
      port: {{ .metric.port }}
      targetPort: {{ .metric.port }}
      name: metric
    {{- end }}
  {{- end }}
  selector:
    {{- include "vsl-rpc.selectorLabels" . | nindent 4 }}