apiVersion: v1
kind: Service
metadata:
  name: {{ template "vsl-rpc.fullname" . }}
  labels:
    {{- include "vsl-rpc.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  {{- with .Values.node.ports.p2p }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      name: p2p
  {{- end }}
  selector:
    {{- include "vsl-rpc.selectorLabels" . | nindent 4 }}