{{- if .Values.broadcaster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.broadcaster.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "rss3-node.broadcaster.fullname" .}}
  labels:
    {{- include "rss3-node.labels" (dict "context" . "component" .Values.broadcaster.name "name" .Values.broadcaster.name) | nindent 4 }}
spec:
  replicas: {{ .Values.broadcaster.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "rss3-node.selectorLabels" (dict "context" . "name" .Values.broadcaster.name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "rss3-node.globalConfigCheckSum" .}}
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.broadcaster.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rss3-node.labels" (dict "context" . "component" .Values.broadcaster.name "name" .Values.broadcaster.name) | nindent 8 }}
 {{- with .Values.broadcaster.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.broadcaster.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rss3-node.hub.ServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.broadcaster.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.broadcaster.name }}
          securityContext:
            {{- toYaml .Values.broadcaster.securityContext | nindent 12 }}
          image: "{{ default .Values.global.image.repository .Values.broadcaster.image.repository }}:{{ .Values.broadcaster.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.broadcaster.image.pullPolicy }}
          args:
            - --module=broadcaster
          resources:
            {{- toYaml .Values.broadcaster.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/rss3-node/deploy
          {{- with .Values.broadcaster.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rss3-node.fullname" . }}
            defaultMode: 0644
      {{- with .Values.broadcaster.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broadcaster.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broadcaster.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broadcaster.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}