apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.hub.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "rss3-node.hub.fullname" .}}
  labels:
    {{- include "rss3-node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 4 }}
spec:
  {{- if not .Values.hub.autoscaling.enabled }}
  replicas: {{ .Values.hub.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "rss3-node.selectorLabels" (dict "context" . "name" .Values.hub.name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "rss3-node.globalConfigCheckSum" .}}
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.hub.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rss3-node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 8 }}
	{{- with .Values.hub.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.hub.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rss3-node.hub.ServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.hub.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.hub.name }}
          securityContext:
            {{- toYaml .Values.hub.securityContext | nindent 12 }}
          image: "{{ default .Values.global.image.repository .Values.hub.image.repository }}:{{ .Values.hub.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.hub.image.pullPolicy }}
          args:
            - --module=hub
          ports:
            - name: http
              containerPort: {{ .Values.hub.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          resources:
            {{- toYaml .Values.hub.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/rss3-node/deploy
          {{- with .Values.hub.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rss3-node.fullname" . }}
            defaultMode: 0644
      {{- with .Values.hub.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
