{{- if .Values.hub.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rss3-node.hub.ServiceAccountName" . }}
  labels:
    {{- include "rss3-node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 4 }}
  {{- with .Values.hub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.hub.serviceAccount.automount }}
{{- end }}
