apiVersion: v1
kind: Service
metadata:
  name: {{ include "serving-node.hub.fullname" . }}
  labels:
    {{- include "serving-node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "serving-node.selectorLabels" (dict "context" . "name" .Values.hub.name) | nindent 4 }}
